services:
  panther_devcontainer:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    runtime: nvidia
    stdin_open: true
    volumes:
      - ../:/home/developer/ros2_ws/src:cached
      - .:/home/developer/ros2_ws:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev:/dev
    environment:
      - DISPLAY
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: sleep infinity